- example/lib/widgets/controls.dart
- example/pubspec.lock
- lib/livekit_client.dart
- lib/src/events.dart
- lib/src/internal/events.dart
- lib/src/participant/local_participant.dart
- lib/src/participant/remote_participant.dart
- lib/src/rtc_engine.dart
- pubspec.lock
- pubspec.yaml
@davidzhao  Should we directly expose PB types `TrackType`, `VideoQuality` ? or just make a public enum and make that public ?
> Organize events

- lib/src/track/options.dart
Fixes https://github.com/livekit/client-sdk-flutter/issues/26
Turns out that the underlying flutter webrtc only looks at `minHeight` and `minWidth` for applying constraints, and otherwise defaults to 720p.
That said, the library will pop an OverconstrainedError if the requested constraints are too high (at least on Chrome, Android I think will automatically find the closest supported format, haven't checked on iOS). Might need to find a way to make the available formats visible to the user or handle that ourselves.
> Use min for width/height to apply constraints

- example/lib/widgets/controls.dart
- lib/src/participant/local_participant.dart
- lib/src/participant/remote_participant.dart
- lib/src/publication/local_track_publication.dart
- lib/src/publication/remote_track_publication.dart
No casting is required anymore for `TrackPublication.track`
`LocalParticipant.videoTracks` returns `List<LocalTrackPublication<LocalVideoTrack>>`
> Type-aware Publication etc (static typing)

- example/lib/widgets/participant.dart
Fix activeVideoTrack to return any unmuted stream, not only first one in the list.
> Fix rendering of remote shared screen

- lib/src/internal/events.dart
- lib/src/publication/local_track_publication.dart
- lib/src/publication/remote_track_publication.dart
- lib/src/publication/track_publication.dart
- lib/src/track/local.dart
- lib/src/track/track.dart
LK-370
Issue https://github.com/livekit/client-sdk-flutter/issues/52
`RemoteTrackPublication.updateFromInfo` was not triggering events... 😞
**Local**
`LocalTrackPublication.mute()` or `LocalTrack.mute()` -> `Track.updateMuted(shouldSendSignal:true)` -> `TrackPublication._onTrackMuteUpdatedEvent()` -> `TrackMutedEvent/TrackUnmutedEvent` emitted.
**Remote**
`RemoteTrackPublication.updateFromInfo` -> `Track.updateMuted(shouldSendSignal:false)` -> `TrackPublication._onTrackMuteUpdatedEvent()` -> `TrackMutedEvent/TrackUnmutedEvent` emitted.
> Fix: mute Remote mute/unmute events

- lib/src/core/engine.dart
- lib/src/internal/events.dart
In addition to publisher ice-connect, 
this PR makes it wait until data channel is `open` state.
> Wait for data channel to `open`

- example/lib/exts.dart
- example/lib/widgets/controls.dart
- example/lib/widgets/participant.dart
- example/macos/Runner.xcodeproj/project.pbxproj
- lib/src/core/engine.dart
- lib/src/core/room.dart
- lib/src/core/signal_client.dart
- lib/src/events.dart
- lib/src/extensions.dart
- lib/src/internal/events.dart
- lib/src/participant/local.dart
- lib/src/publication/remote.dart
- lib/src/types.dart
Still needs more polishing but would appreciate if oniichans could take a look 😁
TODO
- JS is emitting `TrackEvent.Ended`
**Needs testing**
> Subscription permission API

- example/android/app/src/main/AndroidManifest.xml
if you build an APK using the example, it won't connect to the server, it's missing the INTERNET permission on AndroidManifest.xml
> internet permission for example's Manifest

- lib/src/utils.dart
encoding scale calculation was using the wrong side, and ended up getting the wrong numbers (e.g. odd numbers which crash android).
> Fix crash on android in portrait

- lib/src/core/room.dart
- lib/src/publication/remote.dart
`sendSyncState` is already using participantTracks, just for `sendUpdateSubscription`
> Use ParticipantTracks for UpdateSubscription

- lib/src/types.dart
- lib/src/utils.dart
Looks like there's a separate issue where the dimensions we're using for scale calculation may not match the capture format the camera is using, so the even dimensions checking we're using here may still be incorrect.
> Ensure even video dimensions

- lib/src/core/engine.dart
- lib/src/core/room.dart
- lib/src/core/signal_client.dart
- lib/src/internal/events.dart
- Remove redundant internal event
- `Room` also directly listens to `SignalEvents` instead of `Engine` relaying them.
> Simplify internal events

- lib/src/participant/local.dart
- lib/src/track/audio_management.dart
- lib/src/track/local/audio.dart
- lib/src/track/local/local.dart
- lib/src/track/remote/audio.dart
With this change, mute/unmute will not switch audio category just like Swift SDK.
Un-publishing local audio track will stop the mic indicator.
> Change AudioSession configuration logic

- example/lib/pages/connect.dart
@hiroshihorie There should be no problem in submitting the code yesterday, but it seems that `String.fromEnvironment` has a bug. After setting defaultValue, the value of ENV cannot be taken out, so I have submitted the replacement code after the test is correct.
```dart
/// set URL from ENV, url1  is '' or stored value
final url1 = String.fromEnvironment('URL',  defaultValue: prefs.getString(_storeKeyUri) ?? '');
```
change to:
```dart
/// This will work fine
final url1 = const bool.hasEnvironment('URL')
? const String.fromEnvironment('URL')
: prefs.getString(_storeKeyUri) ?? '';
```
So I made a new patch and it shouldn't go wrong this time. :)
> There is a bug in defaultValue in String.fromEnvironment, so replace the code.

- example/pubspec.lock
- pubspec.lock
- pubspec.yaml
Some fixes in this PR:
* Fixed random crash when connecting or disconnecting room under windows
* Fixed the bug that the microphone could not be started normally under Windows.
* Other fixes.
Will close related issues:
close https://github.com/livekit/client-sdk-flutter/issues/121
close https://github.com/livekit/client-sdk-flutter/issues/64
> bump version for flutter_webrtc.

- example/macos/Podfile.lock
- example/pubspec.lock
- pubspec.yaml
fix: macOS cameraLED stays active after stopping a video track
related issue: https://github.com/flutter-webrtc/flutter-webrtc/issues/1000
patch: https://github.com/flutter-webrtc/flutter-webrtc/pull/1002/files
> fix: camera release.

- example/pubspec.lock
- example/pubspec.yaml
- pubspec.yaml
Since the SDK uses the `Enum.name` feature, it is only downgraded to dart 2.15.0, and the corresponding flutter version is 2.8.x
Compilation tests passed in `flutter 2.8.1` and `3.0.2`.
> Downgrade version settings to support flutter 2.8.0+

- example/lib/widgets/participant.dart
fix: The local participant widget cannot respond to the muted state
> fix: close issue #154.

- lib/src/track/options.dart
https://github.com/livekit/client-sdk-flutter/issues/163
- do not set mandatory & optional parameters, when used in web
- web is not allowing it
- adjusted logic to use deviceId over optional parameters in web
> Web - AudioCaptureOptions cant use deviceId and optional parameters

- example/pubspec.lock
- lib/src/core/engine.dart
- pubspec.lock
- pubspec.yaml
Supports getting the connected remote address for verification migration.
Tested platform.
> Supports getting the connected remote address.

- lib/src/core/room.dart
Fixed track not being correctly passed to localParticipant in FastConnectOptions, causing the camera to apply twice and not be released.
close https://github.com/livekit/client-sdk-flutter/issues/178.
> Fixed track not being correctly passed to localParticipant in FastConnectOptions.

- lib/src/core/signal_client.dart
- lib/src/exceptions.dart
Use the error from validate url as the last exception for connection failure.
> fix: Correctly throws final error when connection fails.

- lib/src/support/platform.dart
- lib/src/support/platform/io.dart
- lib/src/support/platform/web.dart
- lib/src/widgets/video_track_renderer.dart
- pubspec.yaml
Bug description (only reproduces in Safari):
After muting the local video track, the remote video track will no longer be displayed.
Not displaying fixed, but causing UI flickering. Still under investigation.
> fix: Fix renderer issue for Safari/Firefox.

- CHANGELOG.md
- lib/src/utils.dart
- pubspec.lock
- pubspec.yaml
* Feat: Support setVideoFPS for subscribe.
* Feat: topic for data-channel.
* Feat: support metadata update.
* Feat: handle reconnect response to re-configuration PCs.
* Docs: readme manager initial setup.
* Feat: upgrade protocol version to v9.
* Chore: Use participantIdentity instead of Sid for track permissions. 
* Feat: Bump flutter-webrtc to 0.9.25.
* Fix: Fix empty label for Wired Headset on Android.
* Fix: ICE Connectivity doesn't establish with DualSIM iPhones.
> new release: 1.2.2

- lib/src/options.dart
- lib/src/participant/local.dart
- lib/src/track/options.dart
- lib/src/types/video_parameters.dart
- lib/src/utils.dart
- pubspec.yaml
* add maintainResolution setting for publish screen sharing track.
* add CaptureOptions for setCameraEnabled/setMicrophoneEnabled/setScreenShareEnabled
* Fix the low bit rate caused by the inability to use the preset encoding parameters when the simulcast is turned off.
* Upgrade flutter-webrtc to 0.9.26, fix the default h264 profile-level-id in iOS/macOS cannot encode 1080p or above resolution.
P.S.
Not sure if it has some issue with simulcast encoding. but after turning off the simulcast, you can get smooth video streaming. will debug again for Android.
https://github.com/livekit/client-sdk-flutter/issues/263
> Fix resolution/framerate/bitrate issue for publishVideoTrack

- lib/src/track/track.dart
When the remote track is stopped, `track.enabled = true|false` should not be called again, in fact, the remote track has been disposed by peerconnection.
close #248.
> fix: Do not operate on inactive tracks.

- CHANGELOG.md
- example/pubspec.yaml
- pubspec.yaml
* Feat: add linux support.
* Fix: audio play bug for ios safari.
* Fix: fix bluetooth device enumerate on android.
* Fix: Do not operate on inactive tracks.
* Fix: use the correct transceiver id.
* Fix: Support restart camera for windows/linux.
* Fix: Move the call of capturer.stopCapture() outside the main thread
to avoid blocking of flutter method call.
* Fix: Handle exceptions for framerate settings for darwin.
close #279 close #257 close #284
> release: 1.3.1.

- example/lib/pages/room.dart
- lib/src/options.dart
I ran into issues with implementation and found that some events were not triggered under RoomEvent. Then I found that I needed to listen to the high level `ParticipantEvent` to ensure my UI was accurate when other peers were unpublishing, muting, etc.
This PR hopefully helps with beginners modeling their own code with this example implementation.
- explaining the different listeners and callbacks
- explaining `FastConnectOptions`
Hoping to help more with this process so that the SDK is not a _leaky abstraction._
> Clarifying events in flutter example: reacting to participant events for updating UI

- example/android/build.gradle
- example/ios/Runner.xcodeproj/project.pbxproj
- example/lib/pages/connect.dart
- lib/src/core/room.dart
- lib/src/options.dart
- lib/src/participant/local.dart
- lib/src/publication/local.dart
- lib/src/track/local/video.dart
- lib/src/utils.dart
- pubspec.lock
* No longer require explicit settings in BackupVideoCodec
* Fix crashes when backupCodec isn't set
* Avoid using default settings, instead use the track's publication options
* Correctly set SVC codec layers
> Bugfixes with multicodec simulcast

- lib/src/participant/local.dart
- lib/src/utils.dart
Casing double to int would cause a crash. Previously this path wasn't exercised because we've always hardcoded preset bitrate for SVC
> Fix SVC codec bitrate computation

- example/ios/Runner.xcodeproj/project.pbxproj
- pubspec.lock
Moving `Embed App Extensions` before `Thin Binary` resolved the build errors.
> Fix iOS example compilation after upgrading to XCode 15.

- lib/src/participant/local.dart
**Expected**
When I pass `false` to `captureScreenAudio`, an audio track should not be created/published to the LiveKit room.
**Actual**
Whenever `captureScreenAudio` is not null, an audio track is always created/published to the LiveKit room regardless of if the variable is `false` or not.
**Fix**
Updated the `captureScreenAudio` conditional to default to `false` if the variable is `null`. Otherwise the actual `true`/`false` value is used for the conditional.
> Fix captureScreenAudio conditional

- lib/src/track/options.dart
**Expected**
When I pass `true` to `useiOSBroadcastExtension`, the screen-share video track should invoke `getDisplayMedia` with constraints containing `deviceId` set to `broadcast`.
**Actual**
When I pass `true` to `useiOSBroadcastExtension`, the screen-share video instead leaves constraint `deviceId` unset because a prior call to `ScreenShareCaptureOptions#copyWith` always sets `useiOSBroadcastExtension` to the default value of `false`.
```dart
/// Creates a LocalTracks(audio/video) from the display.
///
/// The current API is mainly used to capture audio when chrome captures tab,
/// but in the future it can also be used for flutter native to open audio
/// capture device when capturing screen
static Future<List<LocalTrack>> createScreenShareTracksWithAudio([
ScreenShareCaptureOptions? …
```
> Fix iOSBroadcastExtension always false after copyWith invoked

- android/build.gradle
- android/src/main/AndroidManifest.xml
after agp-8.0.0 ,module need to add namespace in build.gradle
https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes
> Update build.gradle for gradle 8.0.0 namespace

- lib/src/support/platform.dart
- lib/src/support/platform/io.dart
- lib/src/support/platform/web.dart
- lib/src/track/local/local.dart
related fix on js  https://github.com/livekit/client-sdk-js/pull/889
> fix: low-resolution screen sharing for safari 17.

- CHANGELOG.md
- ios/livekit_client.podspec
- lib/src/livekit.dart
- macos/livekit_client.podspec
- pubspec.yaml
* Handling of incompatible published codecs.
* Fix/unpublish screen audio track when stop screen share.
* Upgrade connectivity_plus version.
* Fix: low-resolution screen sharing for safari 17.
* Update build.gradle for gradle 8.0.0 namespace.
* Fix captureScreenAudio conditional.
* Fix iOSBroadcastExtension always false after copyWith invoked.
* Fix: VP9 svc screenshare.
* Fix iOS example compilation after upgrading to XCode 15.
* Fix: Crop video output size to target settings (iOS/macOS).
* Fix: Fix bluetooth sco not stopping after room disconnect (Android).
> release: 1.5.3.

- lib/src/participant/local.dart
Unable to obtain the correct height/width from the safari screen sharing track, which will cause Utils.computeVideoLayers to fail and throw an exception.
close https://github.com/livekit/client-sdk-flutter/issues/413
> Fix safari screen sharing failure.

- lib/src/core/engine.dart
- lib/src/core/room.dart
- lib/src/events.dart
- lib/src/internal/events.dart
Removed `RoomRestarting/RoomRestarted` Event and used `RoomReconnecting/RoomReconnected` Event instead
> Do not emit Reconnecting event during the connection resume.

- CHANGELOG.md
- ios/livekit_client.podspec
- lib/src/livekit.dart
- macos/livekit_client.podspec
- pubspec.lock
- pubspec.yaml
There are several breaking changes between v1 and v2. Please consult our [migration guide](https://docs.livekit.io/guides/migrate-from-v1/) when upgrading to v2.
* `Room.participants` was renamed to `Room.remoteParticipants`
* `Room.{audio/video}Tracks` was renamed to `Room.{audio/video}TrackPublications`
* `LocalParticipant.publishData` now uses participant identity as destinations instead of participant sids.
* `Room.sid` now changed to `await room.getSid();`.
* Removed `VideoQuality.OFF` from `VideoQuality` enum.
* `LiveKitClient.connect` - Please use `var room = Room(...)` and `room.connect` instead.
* `track in TrackMutedEvent/TrackUnmutedEvent` - Use `publication` instead
* `TrackStreamStateUpdatedEvent.trackPublication` - Use `TrackStreamStateUpdatedEvent.publication` instead
* …
> release: 2.0.0.

- README.md
- example/android/app/src/main/AndroidManifest.xml
New permission is required for screen share in Android 14:
https://developer.android.com/about/versions/14/changes/fgs-types-required
Fixes #469
> Add Android 14 media projection perm to docs

- lib/src/e2ee/e2ee_manager.dart
- lib/src/e2ee/key_provider.dart
- web/e2ee.cryptor.dart
- web/e2ee.keyhandler.dart
fixes a bug where if you already have keys before setting up the rtp{sender, receiver} framecryptors, they frames use key index 0 by default
> fix: use latest key index for new rtp nodes

- lib/src/participant/local.dart
- lib/src/participant/remote.dart
- pubspec.yaml
After migrating to `package:web`, `AudioElement.srcObject = audioTrack` is called before `createEncodedStreams`, possibly due to `package:web` asynchronous timing changes. Cause E2EE failure.
close https://github.com/livekit/client-sdk-flutter/issues/496
> e2ee: Fix createEncodedStreams failure.

- analysis_options.yaml
- lib/src/track/options.dart
- pubspec.lock
- web/e2ee.cryptor.dart
- web/e2ee.keyhandler.dart
- web/e2ee.logger.dart
- web/e2ee.worker.dart
Logs, cleanup and some fixes, in testing phase rn
> Framecryptor decrypting fixes

- lib/src/track/local/video.dart
close https://github.com/livekit/client-sdk-flutter/issues/514
> fix: get stats exception for local video track.

- lib/src/e2ee/key_provider.dart
- pubspec.lock
- web/e2ee.cryptor.dart
> fix: ratchet on a single frame until ratchetWindowSize

- lib/src/participant/local.dart
Requires https://github.com/flutter-webrtc/flutter-webrtc/pull/1636 to get actual dimensions.
Addresses https://github.com/webrtc-sdk/webrtc/issues/133
> fix: use getSettings() to get actual dimensions for mobile

- lib/src/hardware/hardware.dart
Reverts livekit/client-sdk-flutter#617
and close https://github.com/livekit/client-sdk-flutter/issues/619
> Revert "fix: Fixed speaker cannot be switched on iOS."

- lib/src/widgets/video_track_renderer.dart
use track settings (see also https://github.com/flutter-webrtc/flutter-webrtc/pull/1695) to detect front/back facing camera
> fix: more robust mirror rendering detection

- example/lib/theme.dart
- example/lib/widgets/participant.dart
- example/lib/widgets/participant_info.dart
- example/lib/widgets/participant_stats.dart
- example/lib/widgets/text_field.dart
- lib/src/core/engine.dart
- lib/src/publication/remote.dart
- lib/src/track/options.dart
- lib/src/widgets/video_track_renderer.dart
- pubspec.yaml
The default options for camera will automatically adjust the focus and exposure based on the ambient light. You can also adjust the focus or exposure by tapping the LocalVideoTrack renderer View, or pinching to zoom the camera.
> feat: support FocusMode/ExposureMode for camera capture options.

- example/lib/widgets/controls.dart
- lib/src/core/engine.dart
- lib/src/core/room.dart
- lib/src/core/transport.dart
- lib/src/hardware/hardware.dart
- lib/src/support/native.dart
- lib/src/support/native_audio.dart
- lib/src/track/audio_management.dart
- lib/src/track/track.dart
- lib/src/widgets/video_track_renderer.dart
- shared_swift/LiveKitPlugin.swift
Refer to swift sdk for improvement. By default, `setSpeakerphoneOn(true |false);` will switch between `Receiver` or `Speaker`. It will still give priority to wired `wired/bluetooth` headphones if connected.
But you can ignore all `wired/bluetooth` headphones and force them to output from the speaker through `forceSpeakerOutput: true`.
> fix: Improve speaker switching logic for iOS.

- lib/src/track/local/local.dart
This makes it easy for consumers to zero themselves out on mute, etc. An empty array should be safe, consumers will automatically fill in the zero values based on their expected size.
> Emit a final empty AudioVisualizerEvent after track stops

- lib/src/track/local/video.dart
This fix removes an unnecessary `print("sender stats:")` statement from the logs in the `video.dart` class.
> fix: remove unnecessary debug print statement from logs (Video-Stats)

- lib/src/widgets/video_track_renderer.dart
VideoRenderer display in Screen
When UI Layout changed, then video become black, then display new stream.
So i add a cache renderer, keep video stream side the video renderer, avoid VideoRenderer recreate a new renderer.
> feat: VideoRenderer support cache renderer.

- lib/src/support/platform/web.dart
This PR improves the detection of browser versions across Chrome, Firefox, Safari, Internet Explorer, Web Kit, and Edge. In scenarios where the browser version cannot be parsed, a version number of 0.0.0 is returned.
Fixes https://github.com/livekit/client-sdk-flutter/issues/736
> fix: improve browser version detection

- lib/src/core/room.dart
- lib/src/participant/participant.dart
In fast track publish mode, join and update messages will arrive at the client almost at the same time, so we need to wait for the join process to complete and create the LocalParticipant before processing the update message.
> fix: Fix creation timing for local participant.

- lib/livekit_client.dart
- lib/src/types/attribute-typings.dart
Introduces a new file `attribute-typings.dart` defining Dart classes and enums for agent and transcription attributes, including JSON serialization helpers. Also exports this new typings file from the main library entry point.
> Add attribute typings for agent and transcription

- lib/src/core/room.dart
close https://github.com/livekit/client-sdk-flutter/issues/799
> fix: Always emit RoomDisconnectedEvent when the reason is clientInitiated.

- lib/src/widgets/video_track_renderer.dart
This allows external users to e.g. apply rounded edges. Without this patch, VideoTrackRenderer will expand to its available space with no way (known to me..) for parent widgets to know how large the video actually is.
depends on https://github.com/flutter-webrtc/flutter-webrtc/pull/1754 (and https://github.com/flutter-webrtc/webrtc-interface/pull/30)
> fix: tighten VideoTrackRenderer Widget

- linux/CMakeLists.txt
I ran into a build issue on Linux when using this package. It relies on C++17 features, but without explicitly setting the C++ standard in the package's CMakeLists.txt, the build system was defaulting to an older version.
> Fix linux build error

- lib/src/core/engine.dart
- lib/src/core/room.dart
- lib/src/core/signal_client.dart
- lib/src/participant/local.dart
- lib/src/participant/participant.dart
- lib/src/support/region_url_provider.dart
- web/e2ee.sfi_guard.dart
The timestamp() constructor uses now() + UTC.
> Use UTC timestamps
