README.md, example/macos/Podfile.lock, lib/src/participant/local_participant.dart
=> Send video dimensions to the server

lib/src/track/local.dart
ReplaceTrack is not implemented in flutter_webrtc.
=> Fix mute/unmute on Windows

lib/src/events.dart, lib/src/extensions.dart, lib/src/internal/events.dart, lib/src/publication/remote_track_publication.dart, lib/src/room.dart, lib/src/rtc_engine.dart, lib/src/signal_client.dart, lib/src/types.dart
Flutter ver of https://github.com/livekit/client-sdk-ios/pull/29
=> Stream State Update

lib/src/rtc_engine.dart
=> Separate sub/pub data channels

example/ios/Podfile.lock, example/lib/widgets/participant.dart, example/pubspec.lock, lib/src/internal/events.dart, lib/src/internal/types.dart, lib/src/options.dart, lib/src/publication/remote.dart, lib/src/track/local/local.dart, lib/src/widget/video_track_renderer.dart, pubspec.lock, pubspec.yaml
Should fix issue https://github.com/livekit/client-sdk-flutter/issues/63
Seems to work well but further testing is required.
=> Fix: Visibility Optimization randomly not working

example/lib/exts.dart, example/lib/main.dart, example/lib/widgets/controls.dart, example/macos/Flutter/GeneratedPluginRegistrant.swift, example/macos/Podfile.lock, example/pubspec.lock, lib/livekit_client.dart, lib/src/constants.dart, lib/src/core/engine.dart, lib/src/core/room.dart, lib/src/core/signal_client.dart, lib/src/core/transport.dart, lib/src/extensions.dart, lib/src/internal/events.dart, lib/src/managers/event.dart, lib/src/options.dart, lib/src/participant/local.dart, lib/src/participant/remote.dart, lib/src/publication/local.dart, lib/src/publication/track_publication.dart, lib/src/support/disposable.dart, lib/src/types.dart, lib/src/utils.dart, pubspec.lock, pubspec.yaml, test/livekit_client_test.dart, test/utils_test.dart
Still doing tests 🙂
✅ Using `peerConnectionState` instead of `iceConnectionState`.
Please don't mind some unrelated code.
TODO: Better `DisconnectReason` related logic
TODO: Handle Full reconnect better
=> Session migration

README.md, example/android/app/src/main/AndroidManifest.xml
Support for Bluetooth on Android <11. Fixes #97.
=> Android Bluetooth support

.gitignore, lib/src/core/engine.dart, lib/src/core/room.dart, lib/src/core/signal_client.dart, lib/src/participant/local.dart, lib/src/publication/remote.dart, lib/src/utils.dart, pubspec.lock, test/core/signal_client_test.dart, test/mock/e2e_container.dart
- pass `adaptive_stream` param
- some non-breaking code clean up
=> Pass `adaptive_stream` when connecting

example/README.md, example/lib/pages/connect.dart
Autofill `URL` and `TOKEN` when running in debug mode using mobile devices.
```dart
flutter run --dart-define=URL=ws://192.168.1.141:7880  --dart-define=TOKEN=eyJhbGciOiJIU......
```
=> Autofill URL and TOKEN in debug mode.

lib/src/options.dart, lib/src/participant/local.dart
will test later, before merging I will need to verify that the maxBitrate parameter is passed to the native sdk normally.
=> Add `audioBitrate` option for publishAudioTrack.

lib/src/core/engine.dart, lib/src/core/room.dart, lib/src/core/signal_client.dart, lib/src/participant/remote.dart, lib/src/publication/remote.dart, test/core/room_e2e_test.dart
https://github.com/livekit/client-sdk-js/pull/275
=> handle combined participant update.

pubspec.yaml
=> fix issue #129.

example/lib/pages/connect.dart, example/lib/pages/room.dart, lib/src/core/engine.dart, lib/src/core/room.dart, lib/src/extensions.dart, lib/src/livekit.dart, lib/src/options.dart, lib/src/types/other.dart
I did some tests, we can connect the room in the following two ways
```dart
final room = Room();
final listener = room.createListener();
```
a)
``` dart
await room.connect(
_url,
_token,
roomOptions: RoomOptions(
...
),
fastConnectOptions: _fastConnect
? FastConnectOptions(
microphone: const TrackOption(enabled: true),
camera: const TrackOption(enabled: true),
)
: null,
);
```
b)
```dart
final localAudioTrack = await LocalAudioTrack.create();
final localCamTrack = await LocalVideoTrack.createCameraTrack();
await room.connect(
_url,
_token,
roomOptions: RoomOptions(
...
),
fastConnectOptions: _fastConnect
? FastConnectOptions(
microphone: TrackOption(track: localAudioTrack),
camera:  TrackOption(track: localCamTrack),
)
: null,
);
```
```
=> protocol 8.

README.md
=> Update screen share availability.

example/ios/Podfile.lock, example/macos/Podfile.lock, example/pubspec.lock, ios/livekit_client.podspec, macos/livekit_client.podspec, pubspec.lock, pubspec.yaml
=> chore: update to flutter-webrtc 0.9.2 (m104).

CHANGELOG.md, example/ios/Podfile.lock, example/macos/Podfile.lock, example/pubspec.lock, ios/livekit_client.podspec, macos/livekit_client.podspec, pubspec.yaml
Close: https://github.com/livekit/client-sdk-flutter/issues/150
=> fix: Align the version in .podspec with the package version (fix compilation errors under ios/mac).

lib/src/hardware/hardware.dart
It's useful for Media device to be data class for example in case of selection box.
=> Make MediaDevice data class

CHANGELOG.md, example/pubspec.lock, pubspec.lock, pubspec.yaml
=> release: 1.1.5 (fix-issue-166)

README.md
=> add repair guide for pod install failing.

lib/src/constants.dart, lib/src/core/engine.dart, lib/src/core/transport.dart, lib/src/options.dart, lib/src/participant/remote.dart
close https://github.com/livekit/client-sdk-flutter/issues/182
=> chore: Make timeouts configurable.

lib/src/core/engine.dart, lib/src/extensions.dart
close https://github.com/livekit/client-sdk-flutter/issues/184
=> fix ice config issues.

example/ios/Podfile.lock, example/lib/widgets/controls.dart, example/macos/Podfile.lock, example/pubspec.lock, ios/livekit_client.podspec, lib/src/options.dart, lib/src/participant/local.dart, lib/src/track/audio_management.dart, lib/src/utils.dart, macos/livekit_client.podspec, pubspec.lock, pubspec.yaml
close https://github.com/livekit/client-sdk-flutter/issues/196.
Tested on iPhone.
=> fix: stop audio track on mute.

lib/src/core/room.dart, pubspec.lock, pubspec.yaml
Close https://github.com/livekit/client-sdk-flutter/issues/219
Close https://github.com/livekit/client-sdk-flutter/issues/221
=> fix: fix connection fails for firefox.

lib/src/hardware/hardware.dart
This used to throw a state error because the audio output list is empty under android ( or at least my android device)
=> Fix Audio output list is empty in android

example/lib/widgets/controls.dart
=> [Android] fix screen sharing crash on first boot

ios/livekit_client.podspec, macos/livekit_client.podspec, pubspec.yaml
* fix the bug for firefox.
* fix local camera preview for safari.
* fix not supporting the virtual camera (OBS) for macos. close #230
* fix crash when screen sharing with simulcast on macOS.
=> bug fixes & upgrade

lib/src/track/local/video.dart
=> feat: support fast switch camera for LocalVideoTrack.

example/lib/pages/room.dart, lib/src/core/engine.dart, lib/src/core/room.dart, lib/src/core/signal_client.dart, lib/src/events.dart, lib/src/extensions.dart, lib/src/internal/events.dart, lib/src/types/internal.dart, lib/src/types/other.dart
implementation  for https://github.com/livekit/protocol/pull/139
=> feat: Forward leave reason of disconnected events.

lib/src/core/engine.dart
https://github.com/livekit/client-sdk-js/pull/477
=> fix: set forceRelay if server response is enabled.

example/lib/exts.dart, example/lib/pages/room.dart, lib/src/core/room.dart, lib/src/events.dart
https://github.com/livekit/client-sdk-js/pull/412
=> Room recording event

CHANGELOG.md, macos/livekit_client.podspec, pubspec.yaml
=> release: 1.2.1.

example/lib/widgets/participant.dart, lib/src/publication/remote.dart
https://github.com/livekit/client-sdk-js/pull/484
=> feat: Support setVideoFPS for subscribe.

README.md, analysis_options.yaml, example/analysis_options.yaml, example/android/app/src/main/AndroidManifest.xml, example/lib/pages/connect.dart, example/lib/widgets/controls.dart, example/pubspec.yaml
close https://github.com/livekit/client-sdk-flutter/issues/208
=> fix bluetooth device enumerate.

example/lib/exts.dart, example/lib/pages/room.dart, lib/src/core/room.dart, lib/src/events.dart, lib/src/internal/events.dart, lib/src/participant/remote.dart, lib/src/track/remote/audio.dart, lib/src/track/web/_audio_api.dart, lib/src/track/web/_audio_html.dart, pubspec.yaml
close https://github.com/livekit/client-sdk-flutter/issues/282
when detecting that iOS Safari cannot playback audio, will pop up a dialog box to manually activate the playback.
=> fix: audio play bug for ios safari. 

lib/src/track/local/video.dart, lib/src/track/options.dart, pubspec.yaml
=> fix facingMode for mobile web.

example/lib/pages/connect.dart, lib/src/options.dart, lib/src/participant/local.dart, lib/src/participant/participant.dart, lib/src/participant/remote.dart, lib/src/publication/track_publication.dart, lib/src/track/local/audio.dart, lib/src/track/local/local.dart, lib/src/track/local/video.dart, lib/src/track/remote/audio.dart, lib/src/track/remote/remote.dart, lib/src/track/remote/video.dart, lib/src/track/track.dart
Usage:
```dart
final track = await LocalAudioTrack.create(room.roomOption.defaultAudioCaptureOptions);
await room.publishAudioTrack(track, const AudioPublishOptions(name:'new_audio_track_name_here'));
final track = await LocalVideoTrack.create(room.roomOption.defaultCameraCaptureOptions);
await room.publishVideoTrack(track, const VideoPublishOptions(name:'new_video_track_name_here'));
```
=> fix: add name to AudioPublishOptions.

lib/src/track/local/local.dart, lib/src/track/options.dart
=> feat: add preferCurrentTab support for flutter web.

example/lib/widgets/controls.dart, lib/src/core/transport.dart, lib/src/hardware/hardware.dart, lib/src/support/platform.dart, lib/src/track/audio_management.dart, lib/src/track/options.dart
=> fix SpeakerPhone switch for mobile.

lib/livekit_client.dart, lib/src/hardware/hardware.dart
Close https://github.com/livekit/client-sdk-flutter/issues/327
=> fix: speaker switch for android.

lib/src/track/local/local.dart, lib/src/track/options.dart
close https://github.com/livekit/client-sdk-flutter/issues/337
=> fix: set preferCurrentTab to false bye default

example/lib/widgets/controls.dart, lib/src/hardware/hardware.dart, lib/src/track/audio_management.dart, pubspec.yaml
Revert the changes to around 1.3.5
=> fix: set SpeakerPhone on but prefer Bluetooth.

CHANGELOG.md, lib/src/livekit.dart, pubspec.lock, pubspec.yaml
Close https://github.com/livekit/client-sdk-flutter/issues/334,
Close https://github.com/livekit/client-sdk-flutter/issues/304
=> release: 1.4.2.

example/lib/widgets/controls.dart, example/lib/widgets/no_video.dart, example/lib/widgets/participant.dart, example/lib/widgets/participant_info.dart, example/pubspec.yaml, lib/src/track/web/_audio_context.dart, lib/src/track/web/_audio_html.dart, pubspec.lock, pubspec.yaml
close https://github.com/livekit/client-sdk-flutter/issues/340
=> fix: remove js_bindings and use the built-in AudioContext for js interop.

CHANGELOG.md, ios/livekit_client.podspec, macos/livekit_client.podspec, pubspec.lock, pubspec.yaml
close https://github.com/livekit/client-sdk-flutter/issues/365
close https://github.com/livekit/client-sdk-flutter/issues/369
=> release: 1.5.1.

lib/src/participant/local.dart
close https://github.com/livekit/client-sdk-flutter/issues/385
=> fix: VP9 svc screenshare.

pubspec.lock, pubspec.yaml
For resolve this issue:
[https://github.com/fluttercommunity/plus_plugins/pull/2169](https://github.com/fluttercommunity/plus_plugins/pull/2169)
=> upgrade connectivity_plus version to ^5.0.0

lib/src/participant/local.dart, lib/src/utils.dart
js: https://github.com/livekit/client-sdk-js/pull/911
=> handling of incompatible published codecs

lib/src/track/local/audio.dart, lib/src/track/local/video.dart, lib/src/track/remote/audio.dart, lib/src/track/remote/video.dart
close https://github.com/livekit/client-sdk-flutter/issues/346
=> fix: fix getStats for remote track.

lib/src/publication/track_publication.dart
close https://github.com/livekit/client-sdk-flutter/issues/423.
=> fix: invalid muted state for local publication.

lib/src/core/room.dart
close https://github.com/livekit/client-sdk-flutter/issues/412
=> fix bug for fast connect.

lib/src/core/engine.dart, lib/src/core/signal_client.dart, lib/src/e2ee/key_provider.dart, lib/src/options.dart, lib/src/participant/local.dart, web/e2ee.worker.dart
report log: `operationerror: the operation failed for an operation-specific reason`
=> bug fixes for e2ee (Web/Firefox).

.github/workflows/build.yaml, example/android/app/build.gradle, lib/src/core/transport.dart, lib/src/participant/local.dart, lib/src/utils.dart
corresponding to
https://github.com/livekit/client-sdk-js/pull/1077
and
https://github.com/livekit/client-sdk-js/pull/1079
=> Update screenshare logic for svc publishing

example/lib/widgets/controls.dart, lib/src/participant/local.dart, lib/src/support/platform.dart, lib/src/support/platform/io.dart, lib/src/support/platform/web.dart, lib/src/track/local/video.dart
close https://github.com/livekit/client-sdk-flutter/issues/468
=> Prevent screen-sharing on flutter web mobile.

lib/livekit_client_web.dart, lib/src/internal/events.dart, lib/src/support/websocket/web.dart, lib/src/track/web/_audio_html.dart, pubspec.yaml, web/crypto.dart, web/e2ee.cryptor.dart, web/e2ee.keyhandler.dart, web/e2ee.sfi_guard.dart, web/e2ee.utils.dart, web/e2ee.worker.dart
updates to package:web 
see also: 
https://github.com/flutter-webrtc/flutter-webrtc/pull/1546
=> update to package:web

lib/src/core/engine.dart, lib/src/core/signal_client.dart, lib/src/internal/events.dart, lib/src/utils.dart, pubspec.yaml
close https://github.com/livekit/client-sdk-flutter/issues/502
=> upgrade to connectivity plus 6.x.

CHANGELOG.md, ios/livekit_client.podspec, lib/src/livekit.dart, macos/livekit_client.podspec, pubspec.yaml
This upgrade already supports Flutter 3.19.x. 
If you are using Flutter Web for Firefox, please upgrade Flutter to 3.19.6 or above.
=> release: 2.1.3.

lib/src/core/room.dart, lib/src/participant/local.dart, lib/src/publication/local.dart, lib/src/support/platform.dart, lib/src/track/local/local.dart, lib/src/track/options.dart
This also fallbacks to the default capture options when null
=> feat: provide option to skip stop/restartTrack for mute/unmute

example/lib/pages/room.dart, lib/src/core/room.dart, lib/src/hardware/hardware.dart
close https://github.com/livekit/client-sdk-flutter/issues/376
=> fix iOS AirPods disconnection.

example/lib/pages/room.dart, lib/src/core/room.dart, lib/src/hardware/hardware.dart
Reverts livekit/client-sdk-flutter#518
=> Revert "fix iOS AirPods disconnection."

example/lib/pages/room.dart, example/lib/widgets/controls.dart, lib/src/hardware/hardware.dart, lib/src/track/audio_management.dart, pubspec.yaml
new fix for https://github.com/livekit/client-sdk-flutter/issues/376
=> fix: audio session control for ios.

README.md, example/android/app/build.gradle, example/lib/widgets/controls.dart, pubspec.lock
=> Update example to handle android screenshare permissions for API 34+

CHANGELOG.md, ios/livekit_client.podspec, lib/src/livekit.dart, macos/livekit_client.podspec, pubspec.lock, pubspec.yaml
close https://github.com/livekit/client-sdk-flutter/issues/546
fixed issue:
```
TypeError: Instance of 'LegacyJavaScriptObject': type 'LegacyJavaScriptObject' 
is not a subtype of type 'Map<String, dynamic>'  
using value.videoTrack?.mediaStreamTrack.getSettings()['aspectRatio']
```
=> release: 2.2.1.

lib/src/core/room.dart
close https://github.com/livekit/client-sdk-flutter/issues/553
=> fix room.disconnect issue.

lib/src/events.dart, lib/src/participant/local.dart, lib/src/participant/participant.dart, lib/src/proto/livekit_models.pb.dart, lib/src/proto/livekit_models.pbjson.dart, lib/src/proto/livekit_rtc.pb.dart, lib/src/proto/livekit_rtc.pbenum.dart, lib/src/proto/livekit_rtc.pbjson.dart, lib/src/types/participant_permissions.dart, lib/src/utils.dart
close https://github.com/livekit/client-sdk-flutter/issues/547
=> Add support for participant attributes

analysis_options.yaml, pubspec.yaml, test/core/room_e2e_test.dart, test/core/signal_client_test.dart, test/mock/e2e_container_test.dart
fix analysis to get mor pub points.
=> update lints to 4.0.0.

lib/src/core/room.dart, lib/src/events.dart
Corresponding PR
https://github.com/livekit/client-sdk-swift/pull/459
=> Add timestamps to TranscriptionSegment.

android/build.gradle, example/android/build.gradle
close https://github.com/livekit/client-sdk-flutter/issues/569
=> fix: android build failure.

lib/src/core/engine.dart, lib/src/core/room.dart
close https://github.com/livekit/livekit/issues/2945
=> fix: Handle disconnect reasons correctly.

example/lib/widgets/controls.dart
=> fix: fix speaker switching behavior for android.

CHANGELOG.md, android/build.gradle, example/android/app/build.gradle, example/android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties, example/android/settings.gradle, ios/livekit_client.podspec, macos/livekit_client.podspec, pubspec.yaml, scripts/check_version.dart
close https://github.com/livekit/client-sdk-flutter/issues/648
=> release: 2.3.1+hotfix.1.

shared_swift/Visualizer.swift
=> Fix Swift compilation errors

shared_swift/Visualizer.swift
=> fix Visualizer block UI.

lib/src/track/remote/remote.dart, lib/src/track/track.dart
=> fix track.stop for remote track.

example/lib/main.dart, example/lib/widgets/controls.dart, lib/src/hardware/hardware.dart, pubspec.yaml
close https://github.com/livekit/client-sdk-flutter/issues/659#issuecomment-2563504370
=> fix: bug for speakerPhone switch.

lib/src/hardware/hardware.dart, lib/src/track/track.dart
=> fix issue 683.

example/README.md
@cloudwebrtc can you fact-check this? I'm planning to link here from the overall feature docs as well.
=> E2EE instructions in the example readme

.github/workflows/publish.yaml
Reference https://dart.dev/tools/pub/automated-publishing
=> New pub publish CI workflow

lib/src/core/engine.dart, lib/src/core/room.dart, lib/src/core/signal_client.dart, lib/src/extensions.dart, lib/src/internal/events.dart, lib/src/options.dart, lib/src/participant/local.dart
=> feat: Fast track publication.

example/lib/pages/connect.dart, lib/src/support/platform.dart, lib/src/support/platform/io.dart, lib/src/support/platform/web.dart
=> fix issue 730.

lib/src/track/track.dart
fixes https://github.com/livekit/client-sdk-flutter/issues/721
=> fix: don't close media stream tracks for web

CHANGELOG.md, ios/livekit_client.podspec, lib/src/hardware/hardware.dart, lib/src/livekit.dart, macos/livekit_client.podspec, pubspec.lock, pubspec.yaml
close https://github.com/livekit/client-sdk-flutter/issues/586
close https://github.com/livekit/client-sdk-flutter/issues/735
close https://github.com/livekit/client-sdk-flutter/issues/678
close https://github.com/livekit/client-sdk-flutter/issues/694
=> release: 2.4.2.

lib/src/core/engine.dart
models with known issues: Pixel 7, Galaxy A54
=> fix: fix duplicate fmtp for vp9 on some old Android devices.

CHANGELOG.md, ios/livekit_client.podspec, lib/src/livekit.dart, macos/livekit_client.podspec, pubspec.yaml
* feat: Add smoothTransition option for AudioVisualizer. (#773)
* fix: Fix deadlock when creating a frame cryptor on iOS/macOS.
* fix: add task runner for linux to fix crashes.
close https://github.com/livekit/client-sdk-flutter/issues/652
=> release: 2.4.6.

lib/src/core/engine.dart
see https://github.com/livekit/client-sdk-js/pull/1512
=> Unorder the lossy data channel

lib/src/core/engine.dart
This PR mitigates a reconnect loop that happens via following path:
- a reconnect takes the route through `restartConnection` https://github.com/livekit/client-sdk-flutter/blob/v2.4.6/lib/src/core/engine.dart#L862 (e.g. due to `sendSimulateScenario(fullReconnect: true)`)
- `_setUpSignalListeners` https://github.com/livekit/client-sdk-flutter/blob/v2.4.6/lib/src/core/engine.dart#L888 sets up a callback that will initiate negotiation under certain circumstances (https://github.com/livekit/client-sdk-flutter/blob/v2.4.6/lib/src/core/engine.dart#L980)
- if connection is fast enough (or it is enforced? I'm not 100% sure about the details), the connection of the publisher is setup (https://github.com/livekit/client-sdk-flutter/blob/v2.4.6/lib/src/core/engine.dart#L455) *before* we wait for the …
=> fix: mitigate reconnect loop

pubspec.lock, pubspec.yaml
=> Support protobuf 4

lib/src/hardware/hardware.dart, lib/src/track/audio_management.dart
Related issue: https://github.com/livekit/client-sdk-flutter/issues/796
=> feat: add a flag to skip auto native audio config

lib/src/core/engine.dart, lib/src/core/room.dart
close https://github.com/livekit/client-sdk-flutter/issues/799
=> fix: fix room.disconnect when pending reconnect.

lib/src/widgets/video_track_renderer.dart
Define enum so user's don't need to import flutter_webrtc to specify fit.
=> Enum for VideoViewFit

lib/livekit_client.dart, lib/src/core/room.dart, lib/src/events.dart, lib/src/track/audio_visualizer.dart, lib/src/track/audio_visualizer_native.dart, lib/src/types/transcription_segment.dart
* Move TranscriptionSegment type to separate file
* Use UUIDv4 for visualizer
=> Minor refactoring

android/build.gradle
=> Switch to livekit fork of noise for 16KB page support

android/build.gradle
close https://github.com/livekit/client-sdk-flutter/issues/835
=> hotfix: bump libwebrtc for android

example/ios/Flutter/AppFrameworkInfo.plist, ios/livekit_client.podspec, macos/livekit_client.podspec, pubspec.lock, pubspec.yaml
Fix flutter_webrtc ver to avoid pod-ver conflict.
=> Fix WebRTC pod ver conflict
